### ISSUE TITLE
ResNet-50 codes and pretrained weights

### ISSUE THREAD

**Issue by hao-pt** [facebookresearch/SLIP#16]
In your paper, you said that ```Our improved training procedure achieves 34.6% zero-shot transfer to ImageNet with a modified1 ResNet-50, exceeding the original result of 31.3%.``` 

Might you provide the code of RN-50 with pre-trained weights? Thank you!

**Comment by normster** [comment]
Sorry for the late reply. I don't have the weights available anymore but in terms of code I simply replaced the image encoder with the modified ResNet-50 by the CLIP authors: https://github.com/openai/CLIP/blob/main/clip/model.py#L95. You'll need to plug in the appropriate hyperparameters. I found it easiest to simply inspect their RN50.pt checkpoint to find these values since some definitions and values aren't provided in the paper.
